---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Isaac True

name: sipeed-lichee-rv-gadget
summary: Sipeed Lichee RV gadget
description: |
  Support files for booting the Sipeed Lichee with Ubuntu Core 22
type: gadget
base: core22
assumes: [kernel-assets]
adopt-info: u-boot
architectures:
  - build-on:
      - amd64
      - arm64
      - riscv64
    build-for: riscv64

confinement: strict
compression: lzo

parts:
  u-boot:
    plugin: nil
    stage-packages:
      - u-boot-nezha
    organize:
      usr/lib/u-boot/nezha/u-boot.toc1: u-boot.toc1
    override-stage: |
      craftctl default
      VER=$(strings ${CRAFT_PART_INSTALL}/u-boot.toc1 | grep -E "^U-Boot 20" | cut -f 2 -d\ )
      craftctl set version="${VER}"
      craftctl set grade="devel"
    stage:
      - u-boot.toc1

  # File required by Ubuntu Core
  u-boot-conf:
    plugin: nil
    override-build: |
      touch ${CRAFT_PART_INSTALL}/uboot.conf

  # File required by Ubuntu Core
  boot-sel:
    plugin: nil
    build-packages:
      - u-boot-tools
    override-build: |
      mkenvimage -r -s 4096 -o ${CRAFT_PART_INSTALL}/boot.sel - < /dev/null

  boot-scr:
    plugin: nil
    source: u-boot
    override-build: |
      mkimage -A riscv -T script -C none -n 'Boot Script' -d boot.scr.in ${CRAFT_PART_INSTALL}/boot.scr
    build-packages:
      - sed
      - u-boot-tools

  boot0:
    plugin: nil
    stage-packages:
      - nezha-boot0
    organize:
      usr/lib/u-boot/nezha/boot0_sdcard_sun20iw1p1.bin: boot0_sdcard_sun20iw1p1.bin
    stage:
      - boot0_sdcard_sun20iw1p1.bin

  cloud-init:
    plugin: dump
    source: cloud-init

build-packages:
  - build-essential
  - ccache
  - on riscv64:
    - gcc
  - else:
    - gcc-${CRAFT_ARCH_TRIPLET}
